---
info:
  app:
    description: Cloud Foundry MySQL Service Training
    name: training.cf.services
    version: 0.0.1-SNAPSHOT

training:
  app:
    jwtSecret: jwtTrainingKey
    jwtExpiration: 86400
    
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    beans:
      enabled: true            
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, beans
        
server:
  port: 3000
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trainingdb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: thingtrack
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true 
  application:
    name: Training CF Services